<?php ini_set('display_errors',1);ini_set('display_startup_errors',1);error_reporting(E_ALL);if(isset($_SESSION["username"])){header("location:https://www.consultancynepal.com/cnbackend/dashboard");} ?><!doctypehtml><html lang="en"><head><meta charset="utf-8"><meta content="width=device-width,initial-scale=1,shrink-to-fit=no"name="viewport"><title>Consultancy Nepal LogInPage</title><link href="assets/vendors/iconfonts/font-awesome/css/all.min.css"rel="stylesheet"><link href="assets/vendors/css/vendor.bundle.base.css"rel="stylesheet"><link href="assets/vendors/css/vendor.bundle.addons.css"rel="stylesheet"><link href="assets/css/style.css"rel="stylesheet"><link href="assets/images/favicon.png"rel="shortcut icon"></head><body><div class="container-scroller"><div class="container-fluid full-page-wrapper page-body-wrapper"><div class="align-items-center d-flex auth content-wrapper"><div class="row w-100"><div class="col-lg-4 mx-auto"><div class="auth-form-light p-5 text-left"><?php if(isset($_SESSION["messages"])){echo"<div class='alert alert-danger alert-dismissible fade show' role='alert'>
                    <strong>🥴Error🥴</strong> {$_SESSION['messages']}.
                    <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
                    <span aria-hidden='true'>&times;</span>
                  </button>
                    </div>";unset($_SESSION["messages"]);}elseif(isset($_SESSION['message'])){echo"<div class='alert alert-success alert-dismissible fade show' role='alert'>
    <strong>👍👍success</strong> {$_SESSION['message']}.
    <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
    <span aria-hidden='true'>&times;</span>
  </button>
  </div>";unset($_SESSION['message']);} ?><div class="brand-logo"><img alt="logo"src="images/logo/logo.png"></div><h3 class="font-weight-light">Sign in to continue.</h3><form action="database/actions/login/login.php"class="pt-3"method="post"><div class="form-group"><input class="form-control form-control-lg"id="exampleInputEmail1"name="username"placeholder="Username"></div><div class="form-group"><input class="form-control form-control-lg"id="exampleInputPassword1"name="password"placeholder="Password"type="password"></div><div class="mt-3"><button class="auth-form-btn btn btn-block btn-lg btn-primary font-weight-medium"name="login"type="submit">SIGN IN</button></div><div class="align-items-center d-flex justify-content-between my-2"><a class="auth-link text-black" href="https://www.consultancynepal.com/recover/forgetpassword.php">Forgot password?</a></div></form></div></div></div></div></div></div><script src="assets/vendors/js/vendor.bundle.base.js"></script><script src="assets/vendors/js/vendor.bundle.addons.js"></script><script src="assets/js/off-canvas.js"></script><script src="assets/js/hoverable-collapse.js"></script><script src="assets/js/misc.js"></script><script src="assets/js/settings.js"></script><script src="assets/js/todolist.js"></script></body></html>